### PR TITLE
Blog post on ICMS 2017 workshop

### PR DESCRIPTION
**Pull request by willfurnass**
Work in progress... do not merge yet.

### CODE REVIEW

**Comment by mikecroucher** [comment]
Could we get this completed soon please Will?

**Comment by mikecroucher** [comment]
Are we ready to publish?

**Comment by willfurnass** [comment]
Working on it now

**Comment by willfurnass** [comment]
Didn't mean to merge in those unrelated commits!  Created a new PR (#15) containing just the commits relating to this workshop.  Closing this PR.

**Pull request closed without merging**
