### PR TITLE
Blog post: Software Carpentry and Data Carpentry coming to TUOS

### PR DESCRIPTION
**Pull request by willfurnass**
Started writing a post.

Still need to add content; don't merge yet.

### CODE REVIEW

**Comment by mondus** [comment]
@willfurnass is this post ready to be merged?

**Comment by willfurnass** [comment]
@mondus I got part-way through writing it then thought it best to post it once Tania and I have passed the Software Carpentry 'checkout' process and are certified instructors.

**Comment by mikecroucher** [comment]
Have you passed now?

**Review by trallard — COMMENTED** [review]
nice post @willfurnass I suppose the boss will be happy to merge this now 👍

**Comment by mikecroucher** [comment]
This is very nice :) Thanks.

**Pull request merged**
