### PR TITLE
Added posts about 2nd coffe and cake and adaptive mesh refinement gpu…

### PR DESCRIPTION
**Pull request by twinkarma**
… computing talk.

### CODE REVIEW

**Comment by willfurnass** [comment]
@twinkarma Been drinking 'coffe' whilst talking about Caffe and covfefe? :)

**Comment by twinkarma** [comment]
Whoops, looks like I need more coffee! Or an editor with a proper spell checker.

**Comment by twinkarma** [comment]
Does everything else in the post look ok?

**Comment by willfurnass** [comment]
Yup

**Comment by twinkarma** [comment]
Merge please! Unless Paul/Mike needs to review content?

**Pull request merged**
