### PR TITLE
Added Twin's profile

### PR DESCRIPTION
**Pull request by twinkarma**

### CODE REVIEW

**Comment by twinkarma** [comment]
Pushed my profile to the devel branch before so the site wasn't updating. Now pushing to the master branch.

**Comment by mikecroucher** [comment]
Please only ever push to the devel branch. The master branch is automatically generated by Nikola when you do a GitHub deploy command. @willfurnass can help you out here.

**Comment by willfurnass** [comment]
@twinkarma Submit a pull request against the `devel` branch then once it's been accepted I can run the deploy command necessary to commit a new rendered version of the contents of the `devel` branch to the `master` branch.

**Comment by twinkarma** [comment]
Ah apologies. The devel branch was merged in before but the site was not updating so I thought I had to put it in the master branch. Will do the pull request again.

**Pull request closed without merging**
